config/routes.rb
Rails.application.routes.draw do
  get 'parties/index'

  post 'parties/new' => 'parties/index'

  patch 'parties/edit'

  delete 'parties/delete'

  get 'customers/index'

  post 'customers/new'

  patch 'customers/edit'

  delete 'customers/delete'

  get 'orders/index'

  post 'orders/new'

  patch 'orders/edit'

  delete 'orders/delete'

  get 'promos/index'

  post 'promos/new'

  patch 'promos/edit'

  delete 'promos/delete'

  get 'home/index'

  get 'home/new'

  get 'home/edit'

  get 'home/delete'

  devise_for :users
  root to: "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  def self.create_customer(params)
    Customer.new(
      name: params[:name],
      address: params[:address],
      notes: params[:notes],
      last_hosted: params[:last_hosted],
      attendance: params[:attendance]
    )
  end

  def self.view_customer

  end

  def self.edit_customer

  end

  def self.delete_customer

  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :party
  belongs_to :customer

  def create_order

  end

  def view_order

  end

  def edit_order

  end

  def delete_order

  end
end

app/models/party.rb
class Party < ApplicationRecord
  def create_party

  end

  def view_party

  end

  def edit_party

  end

  def delete_party

  end
end

app/models/promo.rb
class Promo < ApplicationRecord
  belongs_to :party
  belongs_to :customer

  def create_promo

  end

  def view_promo

  end

  def edit_promo

  end

  def delete_promo

  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
    @customer = Customer.new
  end

  def new
    @customer = Customer.create_customer(customer_params)
    if @customer.save
      redirect_to '/customers/index'
    else
      render :json => { errors: @customer.errors.full_messages }, status: 400
    end
  end

  def edit
  end

  def delete
  end

  private

  def customer_params
    params.require(:customer).permit(:name, :address, :notes, :last_hosted, :attendance)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    customers = Customer.all
    promos = Promo.all
    parties = Party.all
    orders = Order.all
    @all_data = [customers, promos, parties, orders]
    # view customers
    # view promos
    # view parties
    # view orders
    # view all??? how do you want to view this.  Blocks? Panels?
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
  end

  def new
  end

  def edit
  end

  def delete
  end
end

app/controllers/parties_controller.rb
class PartiesController < ApplicationController
  def index
  end

  def new
  end

  def edit
  end

  def delete
  end
end

app/controllers/promos_controller.rb
class PromosController < ApplicationController
  def index
  end

  def new
  end

  def edit
  end

  def delete
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customer_helper.rb
module CustomerHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/parties_helper.rb
module PartiesHelper
end

app/helpers/party_helper.rb
module PartyHelper
end

app/helpers/promos_helper.rb
module PromosHelper
end

app/views/customers/delete.html.erb
<h1>Customers#delete</h1>
<p>Find me in app/views/customers/delete.html.erb</p>

app/views/customers/edit.html.erb
<h1>Customers#edit</h1>
<p>Find me in app/views/customers/edit.html.erb</p>

app/views/customers/index.html.erb
<%= form_for @customer, url: customers_new_path do |f| %>
  <%= f.label :name %>:
  <%= f.text_field :name, required: true %><br />

  <%= f.label :address %>:
  <%= f.text_field :address, required: true %><br />

  <%= f.label :notes %>:
  <%= f.text_field :notes %><br />

  <%= f.label :last_hosted %>:
  <%= f.text_field :last_hosted %><br />

  <%= f.label :attendance %>:
  <%= f.text_field :attendance %><br />

  <%= f.submit %>
<% end %>
<button type="button" class="btn btn-primary">Add Customer</button>

app/views/customers/new.html.erb
<p> hi mom

app/views/home/index.html.erb
<h1>Overview</h1>
<p>
  <%= @all_data %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HilltopStampers</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/orders/delete.html.erb
<h1>Orders#delete</h1>
<p>Find me in app/views/orders/delete.html.erb</p>

app/views/orders/edit.html.erb
<h1>Orders#edit</h1>
<p>Find me in app/views/orders/edit.html.erb</p>

app/views/orders/index.html.erb
<h1>Orders#index</h1>
<p>Find me in app/views/orders/index.html.erb</p>

app/views/orders/new.html.erb
<h1>Orders#new</h1>
<p>Find me in app/views/orders/new.html.erb</p>

app/views/parties/delete.html.erb
<h1>Parties#delete</h1>
<p>Find me in app/views/parties/delete.html.erb</p>

app/views/parties/edit.html.erb
<h1>Parties#edit</h1>
<p>Find me in app/views/parties/edit.html.erb</p>

app/views/parties/index.html.erb
<h1>Parties#index</h1>
<p>Find me in app/views/parties/index.html.erb</p>

app/views/parties/new.html.erb
<h1>Parties#new</h1>
<p>Find me in app/views/parties/new.html.erb</p>

app/views/promos/delete.html.erb
<h1>Promos#delete</h1>
<p>Find me in app/views/promos/delete.html.erb</p>

app/views/promos/edit.html.erb
<h1>Promos#edit</h1>
<p>Find me in app/views/promos/edit.html.erb</p>

app/views/promos/index.html.erb
<h1>Promos#index</h1>
<p>Find me in app/views/promos/index.html.erb</p>

app/views/promos/new.html.erb
<h1>Promos#new</h1>
<p>Find me in app/views/promos/new.html.erb</p>